// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-qOuSjPGs0uSv_6fpWI8spx1-4yZrAa4',
    appId: '1:1009137795743:web:283581578e7514cad598aa',
    messagingSenderId: '1009137795743',
    projectId: 'flutter-task-app-8f37d',
    authDomain: 'flutter-task-app-8f37d.firebaseapp.com',
    storageBucket: 'flutter-task-app-8f37d.appspot.com',
    measurementId: 'G-NWN64RXDGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcZvfkFubXKJpJbIDc2AHPeGoRYVpKHZ4',
    appId: '1:1009137795743:android:3624b8ab76ba9e91d598aa',
    messagingSenderId: '1009137795743',
    projectId: 'flutter-task-app-8f37d',
    storageBucket: 'flutter-task-app-8f37d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_yxNqvuHLzI9CyU7avftlJwJqC4e3OE',
    appId: '1:1009137795743:ios:63066a38b598c969d598aa',
    messagingSenderId: '1009137795743',
    projectId: 'flutter-task-app-8f37d',
    storageBucket: 'flutter-task-app-8f37d.appspot.com',
    iosClientId: '1009137795743-2fcnkelfc8tgt89v8cooi4vgv9p32l07.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_yxNqvuHLzI9CyU7avftlJwJqC4e3OE',
    appId: '1:1009137795743:ios:63066a38b598c969d598aa',
    messagingSenderId: '1009137795743',
    projectId: 'flutter-task-app-8f37d',
    storageBucket: 'flutter-task-app-8f37d.appspot.com',
    iosClientId: '1009137795743-2fcnkelfc8tgt89v8cooi4vgv9p32l07.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskapp',
  );
}
